### PR TITLE
fix: correct Neutral gray color choice

### PR DESCRIPTION
**Pull request by rverchere**

### CODE REVIEW

**Review by alixander — COMMENTED** [review]
hmm we have it in our source code as `grey`. Maybe there's a discrepancy somewhere though, where did you notice it should be `gray`?

(https://github.com/terrastruct/d2/blob/master/d2themes/d2themescatalog/neutral_grey.go)

**Comment by BarryNolte** [comment]
https://www.merriam-webster.com/words-at-play/gray-vs-grey-usage-difference

My take is pick one and be consistent.

**Comment by gavin-ts** [comment]
looks like it should be `gray` https://github.com/terrastruct/d2-vscode/issues/62

here it is `gray`:

https://github.com/terrastruct/d2-vscode/blob/40030783aea8854950ae80adf53e9a56791bde19/src/themePicker.ts#L21


https://github.com/terrastruct/d2-playground/blob/master/src/js/modules/theme.js#L7

**Comment by alixander** [comment]
yeah you're right, thank you @rverchere 

Screen Shot 2023-06-16 at 4 55 10 PM

**Review by alixander — APPROVED** [review]

**Comment by rverchere** [comment]
Hi, thanks @alixander ! Indeed I've check the name on the color palette, which is... gray ;)

**Pull request merged**
