### PR TITLE
syntax: Fix substitutions

### LINKED ISSUE #112: spread substitutions
Screen Shot 2023-07-13 at 11 30 39 AM

```d2
vars: {
  base-constraints: [NOT NULL; UNQ]
  disclaimer: DISCLAIMER {
    I am not a lawyer
    near: top-center
  }
}

data: {
  shape: sql_table
  id: int {constraint: [PK; ...${base-constraints}]}
}

custom-disclaimer: DRAFT DISCLAIMER {
  ...${disclaimer}
}
```

### PR DESCRIPTION
**Pull request by nhooyr**
Closes #112

### CODE REVIEW

**Review by gavin-ts — APPROVED** [review]
### before
Screen Shot 2023-07-13 at 1 32 21 PM

### after
Screen Shot 2023-07-13 at 1 31 57 PM

**Review by gavin-ts — CHANGES_REQUESTED** [review]
actually shouldn't `custom-disclaimer` be blue?

looks to be related to:

https://github.com/terrastruct/d2-vscode/assets/85081687/1c792c4a-4e03-4105-b768-6211370191e3

**Comment by nhooyr** [comment]
@gavin-ts test again please

**Review by gavin-ts — APPROVED** [review]
lgtm

Screen Shot 2023-07-13 at 3 08 15 PM

**Pull request merged**
