### PR TITLE
Removes 'import' and adds multiline comment highlighting

### PR DESCRIPTION
**Pull request by BarryNolte**

### CODE REVIEW

**Review by alixander — APPROVED** [review]
sweet, tested and works. 

one minor thing. VSCode seems to default adding a closing double-quote whenever i type a double-quote. Do you know if that's an extension setting that can be turned off? It makes typing out comment blocks a little more cumbersome.

https://github.com/terrastruct/d2-vscode/assets/3120367/bdf69472-b343-442c-baab-7fb61914069c

I tested python which has this style of comments and they seem to have some special handling:

https://github.com/terrastruct/d2-vscode/assets/3120367/390e724d-515b-4e10-9f37-823dbd0f7b0a

But even with no special handling, the default seems that the second instance of typing double quote doesn't add another closing. which is a little more ergonomic too.

https://github.com/terrastruct/d2-vscode/assets/3120367/45616168-eb9d-4257-bf43-242eb86e6ccd

This is pretty minor so no big deal if not obvious.

**Comment by BarryNolte** [comment]
The option to turn off/change the quote behavior is 'Editor: Auto Closing Quotes'.  I think they may have changed this recently, because for about three months, this has been driving me insane.

**Comment by alixander** [comment]
@BarryNolte but the extension has some control over it right? otherwise the behavior wouldn't be different in the above screen recordings given 3 different file extensions

**Comment by BarryNolte** [comment]
I bet you have it set to 'languageDefined'. I have no control ever it.

**Pull request merged**
